apiVersion: v1
kind: Service
metadata:
  name: webapp-backend-service
spec:
  selector:
    app: webapp-backend
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
  type: ClusterIP
