apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "webapp"
  DB_USER: "user"
  NODE_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
type: Opaque
data:
  DB_PASSWORD: "password"
  POSTGRES_PASSWORD: "password"
