apiVersion: v1
kind: Service
metadata:
  name: webapp-frontend-service
spec:
  selector:
    app: webapp-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: 30000
  type: NodePort
