apiVersion: v1
kind: Service
metadata:
  name: webapp-frontend-service
spec:
  selector:
    app: webapp-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
