apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-frontend-deployment
  labels:
    app: webapp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-frontend
  template:
    metadata:
      labels:
        app: webapp-frontend
    spec:
      containers:
        - name: webapp-frontend
          image: webapp-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
